### ISSUE TITLE
interacting with switch

### ISSUE THREAD

**Issue by juancabrio** [ypid/scripts#1]
Hi there, this isnt really an issue but more of a request. 
Could you kindly provide an example of an argument to perform and display a show run ? 
That would be great.  The script works perfectly i just want to expand it and having trouble. 

Thanks very much. 

Juan.

**Comment by ypid** [comment]
There are many scripts in this repo. Which one exactly do you mean? As the README says, you need to read the source in case a script does not have a `--help` option.

**Comment by juancabrio** [comment]
Hi,

Thanks I am looking at ssh-cisco-pexpect.
I think I need to capture stdout if I wanna see the output of a show run
command for example ?

Thanks

Juan.

**Comment by ypid** [comment]
That script was written 6 years ago. Back than it already supported what you want so no change should be needed. That being said, have a look at more modern tools like https://github.com/ytti/oxidized.

A bit off-topic but still worth mentioning. Generate your config with Ansible or SaltStack using https://github.com/netbox-community/netbox/ as source.
